version: '3.6'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  etl:
    build: ./etl/
    depends_on:
      - 'db'
    environment:
      DATABASE_URL: postgres://postgres:@db:5432/postgres
volumes:
  db_data:
